#!/bin/sh
# azd 'postprovision' hook (Linux / macOS / Codespaces).
# Copies the provisioned Foundry model settings into the basic-chat-azure
# example's .env so you can run it immediately.
# Authentication is keyless (Microsoft Entra ID): no API key is written.
set -e

SCRIPT_DIR=$(CDPATH= cd -- "$(dirname -- "$0")" && pwd)
ENV_PATH="$SCRIPT_DIR/../examples/basic-chat-azure/.env"

cat > "$ENV_PATH" <<EOF
# Generated by 'azd provision' (postprovision hook). Do NOT commit this file.
# Authentication is keyless (Microsoft Entra ID) - run 'az login' before running the app.
AZURE_OPENAI_ENDPOINT=${AZURE_OPENAI_ENDPOINT}
AZURE_OPENAI_DEPLOYMENT=${AZURE_OPENAI_DEPLOYMENT}
AZURE_OPENAI_EMBEDDING_DEPLOYMENT=${AZURE_OPENAI_EMBEDDING_DEPLOYMENT}
EOF

echo "Wrote Foundry settings to $ENV_PATH"
