#!/usr/bin/env pwsh
# azd 'postprovision' hook (Windows / pwsh).
# Copies the provisioned Foundry model settings into the basic-chat-azure
# example's .env so you can run it immediately.
# Authentication is keyless (Microsoft Entra ID): no API key is written.
$ErrorActionPreference = 'Stop'

$exampleDir = Join-Path $PSScriptRoot '..\examples\basic-chat-azure'
$envPath = Join-Path $exampleDir '.env'

@"
# Generated by 'azd provision' (postprovision hook). Do NOT commit this file.
# Authentication is keyless (Microsoft Entra ID) - run 'az login' before running the app.
AZURE_OPENAI_ENDPOINT=$($env:AZURE_OPENAI_ENDPOINT)
AZURE_OPENAI_DEPLOYMENT=$($env:AZURE_OPENAI_DEPLOYMENT)
AZURE_OPENAI_EMBEDDING_DEPLOYMENT=$($env:AZURE_OPENAI_EMBEDDING_DEPLOYMENT)
"@ | Set-Content -Path $envPath -Encoding ascii

Write-Host "Wrote Foundry settings to $envPath"
